backend:
  name: github
  repo: garrison0/philterms

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Related Terms", name: "related", widget: "list"}
      - label: "Authors"
        name: "authors" 
        widget: "list"
        fields:
          - {label: First name, name: First name, widget: string}
          - {label: Last name, name: Last name, widget: string} 
  - name: "pageDetails"
    label: "PageDetails"
    files:
      - label: "About Page"
        name: "about"
        file: "content/about.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Update Date", name: "date", widget: "date"}
      - label: "Terms Page"
        name: "terms"
        file: "content/terms.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Update Date", name: "date", widget: "date"}